# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_rotate_joint
    - shoulder_pitch_joint
    - elbow_roll_joint
    - elbow_pitch_joint
    - wrist_roll_joint
    - wrist_pitch_joint
    - eef_roll_joint
    - gripper_leftfinger_joint
    - gripper_rightfinger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_rotate_joint
    - shoulder_pitch_joint
    - elbow_roll_joint
    - elbow_pitch_joint
    - wrist_roll_joint
    - wrist_pitch_joint
    - eef_roll_joint
  gains:
    base_rotate_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    eef_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1